name: FastAPI CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, feature/*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest

      - name: Run Mypy
        run: |
          mypy app

      - name: Run Black
        run: |
          black app tests --check

      - name: Run Isort
        run: |
          isort app tests --check-only
